-- 코드를 작성해주세요
/**
SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (
    SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (
        SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL)
) ORDER BY ID ASC;
*/

SELECT e1.ID FROM ECOLI_DATA e1 
JOIN ECOLI_DATA e2
ON e1.PARENT_ID = e2.ID
JOIN ECOLI_DATA e3
ON e2.PARENT_ID = e3.ID
WHERE e3.PARENT_ID IS NULL 
ORDER BY e1.ID ASC
;