-- 코드를 작성해주세요
/**
SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (
    SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN (
        SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL)
) ORDER BY ID ASC;
*/

/*
SELECT e1.ID FROM ECOLI_DATA e1 
JOIN ECOLI_DATA e2
ON e1.PARENT_ID = e2.ID
JOIN ECOLI_DATA e3
ON e2.PARENT_ID = e3.ID
WHERE e3.PARENT_ID IS NULL 
ORDER BY e1.ID ASC
;*/

WITH RECURSIVE ECOLI_TREE AS (

-- 기본 (Non-Recursive) 파트
SELECT 
    ID,
    PARENT_ID,
    1 GENERATION -- 세대(GENERATION)는 1로 시작함.
FROM 
    ECOLI_DATA
WHERE 
    PARENT_ID IS NULL -- 최상위 노드 (루트 노드)를 찾음.
    
UNION ALL

-- 재귀 (Recursive) 파트
SELECT 
    A.ID,
    A.PARENT_ID,
    B.GENERATION + 1 
FROM 
    ECOLI_DATA A
    INNER JOIN ECOLI_TREE B -- ECOLI_TREE(B)에서 자식 노드(A)를 찾아 계속 붙임.
        ON A.PARENT_ID = B.ID
)

SELECT ID
FROM ECOLI_TREE
WHERE GENERATION = 3 -- 3세대 데이터만 추출
ORDER BY ID