-- 코드를 작성해주세요
SELECT 
CASE 
WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m%d')<DATE_FORMAT("19990401",'%m%d')
THEN '1Q'
WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m%d')<DATE_FORMAT("19990701",'%m%d')
THEN '2Q'
WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m%d')<DATE_FORMAT("19991001",'%m%d')
THEN '3Q'
ELSE '4Q'
END AS QUARTER,
COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA 
GROUP BY QUARTER
ORDER BY QUARTER