SELECT B.HISTORY_ID,
CASE 
    WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 7 
    THEN A.DAILY_FEE* (DATEDIFF(B.END_DATE, B.START_DATE)+1)
    WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 30
    THEN ROUND(A.DAILY_FEE * (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE car_type = '트럭' AND REPLACE(duration_type,'일 이상','') = 7)) / 100 * (DATEDIFF(B.END_DATE, B.START_DATE)+1))
    WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 90 
    THEN ROUND(A.DAILY_FEE * (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE car_type = '트럭' AND REPLACE(duration_type,'일 이상','') = 30)) / 100 * (DATEDIFF(B.END_DATE, B.START_DATE)+1))
    ELSE
    ROUND(A.DAILY_FEE * (100-(SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE car_type = '트럭' AND REPLACE(duration_type,'일 이상','') = 90)) / 100 * (DATEDIFF(B.END_DATE, B.START_DATE)+1))
    END AS 'FEE'
FROM CAR_RENTAL_COMPANY_CAR  A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
-- 코드를 입력하세요
# SELECT REPLACE(duration_type,'일 이상',''), DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE car_type = '트럭';
# SELECT DATEDIFF(B.END_DATE, B.START_DATE)+1 
# FROM CAR_RENTAL_COMPANY_CAR A 
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID = B.CAR_ID
# WHERE CAR_TYPE='트럭';
