-- 코드를 작성해주세요

SELECT 
YEAR(DIFFERENTIATION_DATE) AS YEAR, 
((SELECT MAX(SIZE_OF_COLONY)
 FROM ECOLI_DATA WHERE YEAR = LEFT(DIFFERENTIATION_DATE,4)
GROUP BY DATE_FORMAT("%Y",DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
ID
FROM ECOLI_DATA 
ORDER BY YEAR ASC, YEAR_DEV ASC
;

-- 연도별 가장 큰 대장균의 크기
# SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA
# GROUP BY DATE_FORMAT("%Y",DIFFERENTIATION_DATE)